# Generated by Django 3.1.7 on 2021-04-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_votemodel_vote_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votemodel',
            name='num_downvotes',
        ),
        migrations.RemoveField(
            model_name='votemodel',
            name='num_upvotes',
        ),
        migrations.RemoveField(
            model_name='votemodel',
            name='vote_score',
        ),
    ]
