# Generated by Django 3.1.7 on 2021-04-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210410_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votemodel',
            name='num_downvotes',
        ),
        migrations.RemoveField(
            model_name='votemodel',
            name='num_favorites',
        ),
        migrations.RemoveField(
            model_name='votemodel',
            name='num_upvotes',
        ),
    ]
