# Generated by Django 3.1.7 on 2021-04-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemodel',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
    ]
